### ISSUE TITLE
Datecs Dependencies

### ISSUE THREAD

**Issue by ignaciop000** [payneteasy/reader-example#2]
Hi, where i can downloads this dependencies?

            <dependency>
                <groupId>com.datecs</groupId>
                <artifactId>audioreader</artifactId>
                <version>2.10.73</version>
            </dependency>

thanks you

**Comment by evsinev** [comment]
Hi,

unfortunately Datecs provides their library only after signing NDA.
If you need datecs reader you can ask Datecs partner for it.
Overwise you can exclude this dependency in pom.xml.
